services:
  plt:
    container_name: plt
    working_dir: /app
    build:
      context: .
      args:
        USERNAME: ${username:-plt}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-}
        DISPLAY: ${DISPLAY:-}
      dockerfile: Dockerfile
    image: plt:latest
    user: $USER_UID:$USER_GID
    volumes:
      - ./:/app
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.ssh:/home/${username:-plt}/.ssh:ro
      - ~/.gitconfig:/home/${username:-plt}/.gitconfig:ro
      # - /dev/dri:/dev/dri:cached
    tty: true
    environment:
      XDG_RUNTIME_DIR: /tmp
    env_file:
      - .env
    stdin_open: true